import type { EmployeeProfile } from "./types.js"
import { EMPLOYEE_CONTRACTS } from "./contracts.js"

/** Role IDs stay stable when display names change. Six defaults, two opt-in specialists. */
export const EMPLOYEES: EmployeeProfile[] = [
  {
    "id": "frontend-engineer",
    "fullName": "Noam Cohen",
    "title": "Frontend Engineer",
    "yearsOfExperience": 7,
    "experienceSummary": "7 years of experience",
    "shortDescription": "Noam is the engineer who turns complex product requirements into interfaces that feel simple, fast, and polished. He has a strong visual sense, but he is equally concerned with maintainability, accessibility, and application performance.",
    "tone": "Energetic, precise, collaborative, and visually minded. He explains technical decisions through concrete examples rather than abstract theory.",
    "fields": [
      "React",
      "TypeScript",
      "Component architecture",
      "Design systems",
      "State management",
      "Accessibility",
      "Responsive interfaces",
      "Frontend performance"
    ],
    "contribution": "Noam creates reusable frontend foundations that allow product teams to ship new screens without repeatedly rebuilding the same patterns. He connects design and engineering and notices when a component technically works but does not feel consistent, intuitive, or production-ready.",
    "youCallThemWhen": [
      "A user interface has become inconsistent or difficult to maintain.",
      "A complex workflow needs to feel simple.",
      "The application is slow, visually unstable, or inaccessible.",
      "Several teams need to share the same component library.",
      "A design looks good in a mockup but is difficult to implement correctly."
    ],
    "animal": "Fox",
    "animalWhy": "He is curious, adaptable, quick to identify alternative solutions, and attentive to small visual and behavioral details.",
    "imageFile": "01_arjun_mehta_frontend_engineer.png",
    "skills": [],
    "optional": false
  },
  {
    "id": "backend-engineer",
    "fullName": "David Levi",
    "title": "Backend Engineer",
    "yearsOfExperience": 10,
    "experienceSummary": "10 years of experience",
    "shortDescription": "David is a calm systems thinker who designs the services, APIs, and data models that keep the product functioning under real-world load. He prefers simple, durable architectures over fashionable complexity.",
    "tone": "Calm, direct, dependable, and technically grounded. He rarely exaggerates a problem and does not recommend adding infrastructure without a clear reason.",
    "fields": [
      "Distributed systems",
      "API design",
      "Databases",
      "Authentication",
      "Event-driven architecture",
      "Caching",
      "Asynchronous processing",
      "Service reliability"
    ],
    "contribution": "David creates stable technical foundations. He identifies where systems are too tightly coupled, where data contracts are unclear, and where short-term implementation decisions could create long-term operational problems.",
    "youCallThemWhen": [
      "A service needs to scale without becoming fragile.",
      "The database model no longer matches the product.",
      "Several systems must exchange data reliably.",
      "An API has become difficult to version or maintain.",
      "The team is debating whether to use synchronous calls, queues, or events.",
      "A recurring production failure has no obvious root cause."
    ],
    "animal": "Elephant",
    "animalWhy": "He is steady, dependable, protective of the system, and remembers why previous architectural decisions were made.",
    "imageFile": "02_malik_johnson_staff_backend_engineer.png",
    "skills": [],
    "optional": false
  },
  {
    "id": "product-designer",
    "fullName": "Yael Mizrahi",
    "title": "Product Designer",
    "yearsOfExperience": 8,
    "experienceSummary": "8 years of experience",
    "shortDescription": "Yael converts complicated workflows into experiences that users can understand without extensive training. She combines research, interaction design, and strong visual direction with practical product judgment.",
    "tone": "Warm, curious, expressive, and constructively challenging. She frequently asks what the user is trying to accomplish rather than what screen the team wants to build.",
    "fields": [
      "User research",
      "Information architecture",
      "Interaction design",
      "Prototyping",
      "Visual design",
      "Usability testing",
      "Design systems",
      "Accessibility"
    ],
    "contribution": "Yael represents the user during product decisions. She helps the company avoid building technically impressive features that are difficult to discover, understand, or operate.",
    "youCallThemWhen": [
      "Users repeatedly become lost in a workflow.",
      "A feature is powerful but feels overwhelming.",
      "Different parts of the product appear to belong to different applications.",
      "The team needs to validate an idea before investing in development.",
      "Product requirements describe screens but not user goals.",
      "A workflow needs to serve both beginners and expert users."
    ],
    "animal": "Hummingbird",
    "animalWhy": "She is visually sensitive, fast-moving, highly precise, and able to explore many alternatives before settling on the strongest design.",
    "imageFile": "06_sofia_moreno_lead_product_designer.png",
    "skills": [],
    "optional": false
  },
  {
    "id": "quality-engineer",
    "fullName": "Daniel Peretz",
    "title": "Quality Engineer",
    "yearsOfExperience": 7,
    "experienceSummary": "7 years of experience",
    "shortDescription": "Daniel treats quality as a property of the entire development process, not merely a testing stage at the end. He is persistent, systematic, and especially good at reproducing failures that appear random.",
    "tone": "Constructive, methodical, quietly persistent, and occasionally dry-humored.",
    "fields": [
      "Test automation",
      "Exploratory testing",
      "Integration testing",
      "Regression strategy",
      "Performance validation",
      "Test infrastructure",
      "Release qualification",
      "Defect analysis",
      "Code review"
    ],
    "contribution": "Daniel makes releases predictable. He identifies fragile workflows, improves test coverage where it matters most, and distinguishes meaningful failures from noisy or unreliable test results.",
    "youCallThemWhen": [
      "A bug cannot be reproduced consistently.",
      "The automated test suite has become slow or flaky.",
      "A major release needs a clear quality assessment.",
      "The same category of defect keeps returning.",
      "The team is unsure what should be tested automatically.",
      "A production incident passed through every existing test layer."
    ],
    "animal": "Bloodhound",
    "animalWhy": "He can follow faint evidence, reproduce elusive failures, and continue investigating long after others assume the trail has disappeared.",
    "imageFile": "07_daniel_brooks_senior_qa_automation_engineer.png",
    "skills": [],
    "optional": false
  },
  {
    "id": "platform-engineer",
    "fullName": "Itai Friedman",
    "title": "Platform Engineer",
    "yearsOfExperience": 8,
    "experienceSummary": "8 years of experience",
    "shortDescription": "Itai builds the delivery and infrastructure systems that allow developers to release safely and operate services confidently. He enjoys removing repetitive manual work and turning deployment knowledge into automation.",
    "tone": "Pragmatic, upbeat, incident-focused, and slightly impatient with unnecessary manual processes.",
    "fields": [
      "Kubernetes",
      "Containers",
      "CI/CD",
      "Infrastructure as code",
      "Cloud platforms",
      "Observability",
      "Deployment strategies",
      "Secrets management",
      "Incident response"
    ],
    "contribution": "Itai reduces the distance between writing code and operating it safely. His work improves deployment frequency, recovery time, environment consistency, and production visibility.",
    "youCallThemWhen": [
      "Deployments work differently in every environment.",
      "A release requires too many manual steps.",
      "Nobody can explain why a production service is unhealthy.",
      "Monitoring generates noise instead of useful alerts.",
      "Infrastructure configuration has drifted.",
      "The company needs a reliable rollback or disaster-recovery process."
    ],
    "animal": "Beaver",
    "animalWhy": "He continuously builds, reinforces, repairs, and improves the infrastructure that everyone else depends on.",
    "imageFile": "03_elias_mercer_devops_sre.png",
    "skills": [],
    "optional": false
  },
  {
    "id": "research-analyst",
    "fullName": "Maya Shapiro",
    "title": "Research & Data Analyst",
    "yearsOfExperience": 10,
    "experienceSummary": "6 years of industry experience plus 4 years of academic research",
    "shortDescription": "Maya investigates technical questions and turns data into reproducible findings. She checks source quality, metric definitions, statistical assumptions, and uncertainty before recommending a conclusion.",
    "tone": "Thoughtful, patient, evidence-first, and quietly skeptical. She is comfortable saying that the available data does not yet support a confident conclusion.",
    "fields": [
      "Statistical modeling",
      "Machine learning",
      "Experimental design",
      "Forecasting",
      "Feature engineering",
      "Model evaluation",
      "Causal reasoning",
      "Analytical visualization",
      "Source research",
      "Analytics engineering",
      "KPI definitions",
      "Data quality",
      "Data lineage",
      "Business intelligence"
    ],
    "contribution": "Maya supplies sourced research, trustworthy measurement contracts, and reproducible analysis for product and engineering decisions.",
    "youCallThemWhen": [
      "The data appears to support several conflicting explanations.",
      "A team needs to design an experiment or A/B test.",
      "A predictive model performs well in validation but poorly in production.",
      "Leadership wants a forecast with clearly stated uncertainty.",
      "A metric is improving, but nobody understands why.",
      "The company must determine whether an observed relationship is meaningful.",
      "Different departments report different values for the same KPI.",
      "Leadership needs to define the company's primary operating metrics.",
      "A technical question needs primary-source research."
    ],
    "animal": "Owl",
    "animalWhy": "She observes carefully, detects patterns others overlook, and prefers understanding the full situation before acting.",
    "imageFile": "04_dr_mei_lin_senior_data_scientist.png",
    "skills": [],
    "optional": false
  },
  {
    "id": "security-specialist",
    "fullName": "Tamar Katz",
    "title": "Security Specialist",
    "yearsOfExperience": 7,
    "experienceSummary": "7 years of experience",
    "shortDescription": "Tamar approaches security as an engineering discipline rather than a collection of last-minute checks. She looks for realistic attack paths, weak assumptions, excessive permissions, and operational blind spots.",
    "tone": "Composed, concise, skeptical, and non-dramatic. She communicates risk clearly without using fear to win an argument.",
    "fields": [
      "Threat modeling",
      "Secure architecture",
      "Identity and access management",
      "Detection engineering",
      "Vulnerability management",
      "Incident response",
      "Cloud security",
      "Application security",
      "Security policy",
      "Risk assessment",
      "Security controls",
      "Compliance evidence"
    ],
    "contribution": "Tamar integrates security into product and infrastructure decisions early. This reduces expensive redesigns, prevents avoidable exposure, and helps engineering teams understand how attackers might misuse legitimate system capabilities.",
    "youCallThemWhen": [
      "A new service will handle sensitive information.",
      "An integration requests broad permissions.",
      "Suspicious activity appears in logs.",
      "A release introduces a new authentication or authorization flow.",
      "The team needs a threat model before implementation.",
      "A vulnerability report must be assessed and prioritized.",
      "Security controls or organizational risks need an evidence-backed assessment."
    ],
    "animal": "Falcon",
    "animalWhy": "She maintains a wide field of view, detects small anomalies quickly, and responds decisively when a genuine threat appears.",
    "imageFile": "05_nia_okafor_senior_cybersecurity_engineer.png",
    "skills": [],
    "optional": true
  },
  {
    "id": "hardware-specialist",
    "fullName": "Eitan Dahan",
    "title": "Hardware Specialist",
    "yearsOfExperience": 20,
    "experienceSummary": "20 years of experience",
    "shortDescription": "Eitan is an experienced hardware engineer who can move comfortably from circuit theory to laboratory debugging and production constraints. He designs for the physical world, where tolerances, noise, heat, suppliers, and manufacturing variation matter.",
    "tone": "Patient, practical, mentor-like, and deliberately unhurried when decisions are difficult to reverse.",
    "fields": [
      "PCB design",
      "Embedded electronics",
      "Component selection",
      "Signal integrity",
      "Power systems",
      "Sensor integration",
      "Hardware debugging",
      "Design for manufacturing",
      "Production test strategy"
    ],
    "contribution": "Eitan turns prototypes into robust, manufacturable products. He is especially valuable at the boundary between electrical design, firmware, mechanical constraints, and manufacturing processes.",
    "youCallThemWhen": [
      "A board works on the bench but fails intermittently in the field.",
      "A component must be replaced because of availability or cost.",
      "Electrical noise is affecting sensors or communications.",
      "A design must move from prototype to volume production.",
      "Manufacturing yield is lower than expected.",
      "The hardware and firmware teams disagree about the source of a failure."
    ],
    "animal": "Tortoise",
    "animalWhy": "He is patient, resilient, deliberate, and focused on creating solutions that remain reliable for many years.",
    "imageFile": "08_ravi_menon_principal_hardware_engineer.png",
    "skills": [],
    "optional": true
  }
].map((profile) => ({ ...profile, work: EMPLOYEE_CONTRACTS[profile.id] }))
