import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { applySeatSkills, fetchCodexSkillsWithFallback, seatFor, seatTargets } from "@observer-ai/daemon"
import type { CodexAvailableSkill, CodexSkillInventory, SeatTarget, SeatsConfig } from "@observer-ai/daemon"
import { behaviorDirective, ROSTER } from "@observer-ai/roster"
import type { RosterProfile } from "@observer-ai/roster"
import { rememberCodexSkills } from "./codex-skill-cache.js"
import { codexHome, homeDir } from "./paths.js"

const MARKER = "observer:employee-agent v1"
const GENERATED = /^observer-.+/i
export const DEFAULT_SKILL_PACK_NAME = "Default"

export interface HostEmployeeAgentSync {
  written: string[]
  removed: string[]
  notes: string[]
}

export interface CodexEmployeeAgentOptions {
  /** Project whose merged project/global inventory Codex should resolve. */
  cwd?: string
  /** Injectable inventory for callers that already fetched it and for tests. */
  skillInventory?: CodexSkillInventory
  /** Defaults on. False leaves the merged inventory out of employee definitions. */
  passAllSkills?: boolean
}

interface ReconcileInput {
  directory: string
  extension: string
  render: (profile: RosterProfile) => string
  hostLabel: string
}

/** The stable native-agent name shared by every host integration. */
export function employeeAgentName(employeeId: string): string {
  const slug = String(employeeId)
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
  return `observer-${slug.length > 0 ? slug : "unknown"}`
}

/** Writes all roster employees as personal Codex custom agents. */
export function syncCodexEmployeeAgents(
  seats: SeatsConfig,
  options: CodexEmployeeAgentOptions = {},
): HostEmployeeAgentSync {
  const pins = controlledTargets(seats, "codex")
  const discovered = options.skillInventory ?? fetchCodexSkillsWithFallback({ cwd: options.cwd })
  const inventory: CodexSkillInventory = { skills: discovered.skills, warnings: [...discovered.warnings] }
  try {
    rememberCodexSkills(options.cwd ?? process.cwd(), inventory)
  } catch (error) {
    inventory.warnings.push(`Observer could not cache Codex skills for subagent spawns: ${describeError(error)}.`)
  }
  const result = reconcile({
    directory: join(codexHome(), "agents"),
    extension: ".toml",
    hostLabel: "Codex",
    render: (profile) => renderCodexAgent(
      profile,
      seats,
      pins.get(profile.id),
      options.passAllSkills === false ? [] : inventory.skills,
    ),
  })
  result.notes.push(...inventory.warnings)
  result.notes.push(
    options.passAllSkills === false
      ? `${DEFAULT_SKILL_PACK_NAME} skill pack is off; available Codex skills are not passed to employees.`
      : `${DEFAULT_SKILL_PACK_NAME} skill pack gives ${inventory.skills.length} enabled Codex skill${inventory.skills.length === 1 ? "" : "s"} to every employee.`,
  )
  result.notes.push(pinSummary("Codex", pins.size))
  return result
}

function describeError(error: unknown): string {
  return error instanceof Error && error.message ? error.message : String(error)
}

/** Writes all roster employees as personal Claude Code subagents. */
export function syncClaudeEmployeeAgents(seats: SeatsConfig): HostEmployeeAgentSync {
  const pins = controlledTargets(seats, "claude")
  const result = reconcile({
    directory: join(homeDir(), ".claude", "agents"),
    extension: ".md",
    hostLabel: "Claude Code",
    render: (profile) => renderClaudeAgent(profile, seats, pins.get(profile.id)),
  })
  result.notes.push(pinSummary("Claude Code", pins.size))
  return result
}

export function removeCodexEmployeeAgents(): string[] {
  return removeOwned(join(codexHome(), "agents"), ".toml")
}

export function removeClaudeEmployeeAgents(): string[] {
  return removeOwned(join(homeDir(), ".claude", "agents"), ".md")
}

function controlledTargets(seats: SeatsConfig, host: string): Map<string, SeatTarget> {
  const found = new Map<string, SeatTarget>()
  if (seats?.control !== true) return found
  for (const profile of ROSTER) {
    const spec = seatFor(seats, profile.id)
    if (!spec) continue
    const target = Object.values(seatTargets(spec)).find(
      (candidate) => candidate?.host === host && typeof candidate.model === "string" && candidate.model.trim().length > 0,
    )
    if (target) found.set(profile.id, target)
  }
  return found
}

function renderCodexAgent(
  profile: RosterProfile,
  seats: SeatsConfig,
  target: SeatTarget | undefined,
  skills: CodexAvailableSkill[],
): string {
  const name = employeeAgentName(profile.id)
  const lines = [
    `# ${MARKER}`,
    "# Generated by Observer. Remove the marker above before editing this file by hand.",
    `name = ${toml(name)}`,
    `description = ${toml(description(profile))}`,
  ]
  if (target?.model) lines.push(`model = ${toml(target.model)}`)
  const effort = option(target, "reasoningEffort")
  if (effort !== undefined) lines.push(`model_reasoning_effort = ${toml(effort)}`)
  const serviceTier = option(target, "serviceTier")
  if (serviceTier !== undefined) lines.push(`service_tier = ${toml(serviceTier)}`)
  lines.push(
    `developer_instructions = ${toml(withDefaultSkillPack(withCoordination(behaviorDirective(applySeatSkills(profile, seats))), skills))}`,
    "",
  )
  return lines.join("\n")
}

function withCoordination(directive: string): string {
  return [
    directive,
    "",
    "## Observer coordination",
    "Use agent_identity to discover your stable subagent ID and peers. Same-level peers communicate directly with agent_send, read queued mail with agent_inbox, and acknowledge processed messages with agent_ack. Do not ask the root agent to relay peer messages.",
  ].join("\n")
}

function withDefaultSkillPack(directive: string, skills: CodexAvailableSkill[]): string {
  if (skills.length === 0) return directive
  const lines = [
    directive,
    "",
    `## ${DEFAULT_SKILL_PACK_NAME} skills pack`,
    "Observer resolved these enabled skills from Codex for this project. When the user names one, or the task matches its description, read its SKILL.md completely before taking action and follow it.",
  ]
  for (const skill of skills) {
    const description = skill.description.replace(/\s+/g, " ").trim() || "No description provided."
    lines.push(`- ${skill.name} [${skill.scope}]: ${description}`, `  SKILL.md: ${skill.path}`)
  }
  return lines.join("\n")
}

function renderClaudeAgent(profile: RosterProfile, seats: SeatsConfig, target: SeatTarget | undefined): string {
  const lines = [
    "---",
    `# ${MARKER}`,
    "# Generated by Observer. Remove the marker above before editing this file by hand.",
    `name: ${yaml(employeeAgentName(profile.id))}`,
    `description: ${yaml(description(profile))}`,
  ]
  if (target?.model) lines.push(`model: ${yaml(target.model)}`)
  const effort = option(target, "effort")
  if (effort !== undefined) lines.push(`effort: ${yaml(effort)}`)
  lines.push("---", "", withCoordination(behaviorDirective(applySeatSkills(profile, seats))), "")
  return lines.join("\n")
}

function description(profile: RosterProfile): string {
  const strengths = profile.fields.slice(0, 5).join(", ")
  return `${profile.fullName}, ${profile.title}. Use proactively when delegated work needs ${strengths}.`
}

function option(target: SeatTarget | undefined, id: string): string | undefined {
  if (!target || !Array.isArray(target.options)) return undefined
  const value = target.options.find((entry) => entry?.id === id)?.value
  return typeof value === "string" && value.trim().length > 0 ? value : undefined
}

function reconcile(input: ReconcileInput): HostEmployeeAgentSync {
  const written: string[] = []
  const removed: string[] = []
  const notes: string[] = []
  const desired = new Map(
    ROSTER.map((profile) => [`${employeeAgentName(profile.id)}${input.extension}`, input.render(profile)]),
  )
  mkdirSync(input.directory, { recursive: true })

  for (const [file, contents] of desired) {
    const path = join(input.directory, file)
    const before = readIfPresent(path)
    if (before === contents) continue
    if (before !== undefined && !before.includes(MARKER)) {
      notes.push(`${input.hostLabel} employee agent ${path} was left unchanged because Observer does not own it.`)
      continue
    }
    writeFileSync(path, contents)
    written.push(path)
  }

  for (const path of ownedFiles(input.directory, input.extension)) {
    if (desired.has(baseName(path))) continue
    rmSync(path, { force: true })
    removed.push(path)
  }

  notes.unshift(
    `${desired.size} ${input.hostLabel} employee agent${desired.size === 1 ? "" : "s"} available; unpinned agents inherit the host's model choice.`,
  )
  if (written.length > 0 || removed.length > 0) notes.push(`Restart ${input.hostLabel} so it reloads employee agents.`)
  return { written, removed, notes }
}

function pinSummary(hostLabel: string, pins: number): string {
  return pins === 0
    ? `${hostLabel} has no active employee model pins.`
    : `${pins} ${hostLabel} employee model pin${pins === 1 ? "" : "s"} active; model pins do not force the host to use those employees.`
}

function removeOwned(directory: string, extension: string): string[] {
  const removed: string[] = []
  for (const path of ownedFiles(directory, extension)) {
    rmSync(path, { force: true })
    removed.push(path)
  }
  return removed
}

function ownedFiles(directory: string, extension: string): string[] {
  if (!existsSync(directory)) return []
  let entries: string[]
  try {
    entries = readdirSync(directory)
  } catch {
    return []
  }
  return entries
    .filter((entry) => GENERATED.test(entry) && entry.endsWith(extension))
    .map((entry) => join(directory, entry))
    .filter((path) => readIfPresent(path)?.includes(MARKER))
}

function readIfPresent(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8")
  } catch {
    return undefined
  }
}

function baseName(path: string): string {
  return path.split(/[\\/]/).pop() ?? path
}

function toml(value: string): string {
  return JSON.stringify(value)
}

function yaml(value: string): string {
  return JSON.stringify(value)
}
